version: '3'
services:
  postgres:
    image: postgres:13
    expose:
      - "5432"
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD"
      - "POSTGRES_USER"
      - "POSTGRES_DB"

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    expose:
      - "6379"

  elastic:
    image: elasticsearch:7.17.1
    ports:
      - "9200:9200"
    expose:
      - "9200"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"

  async_api:
    build:
      context: ./
    image: async-api-image
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - redis
      - elastic

  tests:
    image: async-api-image
    network_mode: "host"
    environment:
      - PYTHONPATH=/app
    entrypoint: >
      sh -c "pip install -r ./tests/functional/requirements.txt
      && python3 ./tests/functional/utils/wait_for_es.py
      && python3 ./tests/functional/utils/wait_for_redis.py
      && pytest ./tests/functional/src"
    depends_on:
      - redis
      - elastic
      - async_api
